version: '2'

services:
  reactive-flows:
    image: hseeberger/reactive-flows:latest
    ports:
      - 8000
    command: [
      "-Dcassandra-journal.contact-points.0=cassandra:9042",
      "-Dconstructr.coordination.host=etcd"
    ]
    shm_size: 256m

  cassandra:
    image: cassandra:3.10
    ports:
      - "9042:9042"

  etcd:
    image: quay.io/coreos/etcd:v2.3.7
    ports:
      - "2379:2379"
    command: [
      "--advertise-client-urls",
      "http://etcd:2379",
      "--listen-client-urls",
      "http://0.0.0.0:2379"
    ]
